name: Publish to Nexus Repository

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Decode and import GPG key (if signing is enabled)
        if: env.GPG_PRIVATE_KEY != ''
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Determine Nexus Repository
        id: repo
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "REPO_URL=https://repo.negative.games/releases/" >> $GITHUB_ENV
          else
            echo "REPO_URL=https://repo.negative.games/snapshots/" >> $GITHUB_ENV
          fi

      - name: Publish to Nexus
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.NEXUS_PASSWORD }}
