name: Deploy to Nexus Repository

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Configure Gradle
        run: |
          echo "nexusUsername=${{ secrets.NEXUS_USERNAME }}" >> ~/.gradle/gradle.properties
          echo "nexusPassword=${{ secrets.NEXUS_PASSWORD }}" >> ~/.gradle/gradle.properties

      - name: Build and deploy snapshot
        if: github.event_name == 'push'
        run: ./gradlew publish -PnexusUrl=https://repo.negative.games/repository/skylands

      - name: Build and deploy release
        if: github.event_name == 'release'
        run: ./gradlew publish -PnexusUrl=https://repo.negative.games/repository/skylands